server:
  port: 6000
spring:
  profiles:
    active: "test"
    
    
resilience4j.circuitbreaker:
    instances:
        default:
            permittedNumberOfCallsInHalfOpenState: 3
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 50s
            failureRateThreshold: 70

resilience4j.bulkhead:
    instances:
        default:
            maxWaitDuration: 10ms
            maxConcurrentCalls: 10