INSERT INTO TB_PRODUCT(ID,URL_IMG,DESCRIPTION,NAME,PRICE) VALUES('1',' ','PS5 PRO-X','PS5',10.0);
INSERT INTO TB_PRODUCT(ID,URL_IMG,DESCRIPTION,NAME,PRICE) VALUES('2',' ','PC GAMER SUPER','DESCKTOP',50.0);
INSERT INTO TB_PRODUCT(ID,URL_IMG,DESCRIPTION,NAME,PRICE) VALUES('3',' ','BATATEIRA SUPER','BATATEIRA',150.0);
INSERT INTO TB_PRODUCT(ID,URL_IMG,DESCRIPTION,NAME,PRICE) VALUES('4',' ','MICROONDAS SMART','MICROONDAS',50.0);
INSERT INTO TB_PRODUCT(ID,URL_IMG,DESCRIPTION,NAME,PRICE) VALUES('5',' ','MONITOR CURVO ','MONITOR',500.0);
INSERT INTO TB_PRODUCT(ID,URL_IMG,DESCRIPTION,NAME,PRICE) VALUES('6',' ','TECLADO COM LEDS','TECLADO',250.0);
