server:
  port: 7000
spring:
  profiles:
    active: "test"
    
    
resilience4j.circuitbreaker:
    instances:
        backendB:
            permittedNumberOfCallsInHalfOpenState: 3
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 50s
            failureRateThreshold: 70

            