server:
  port: 7000
spring:
  profiles:
    active: "test"
  
resilience4j.circuitbreaker:
    instances:
        interfaceFindCartByIdInCartService:
            permittedNumberOfCallsInHalfOpenState: 3
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 50s
            failureRateThreshold: 70

resilience4j.bulkhead:
    instances:
        interfaceFindCartByIdInCartService:
            maxWaitDuration: 10ms
            maxConcurrentCalls: 10