spring:
  profiles:
    active: "test"
server:
  port: 7000
resilience4j.circuitbreaker:
    instances:
        interfaceFindCartByIdInCartService:
            permittedNumberOfCallsInHalfOpenState: 2
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 120s
            failureRateThreshold: 70
            slowCallRateThreshold: 70
            slowCallDurationThreshold: 2s

resilience4j.bulkhead:
    instances:
        interfaceFindCartByIdInCartService:
            maxWaitDuration: 10s
            maxConcurrentCalls: 3
feign:
    client:
        config.default.connectTimeout: 3000
        config.default.readTimeout: 3000