server:
  port: 9000
spring:
  profiles:
    active: "test"
      
resilience4j:
  bulkhead:
   instances:
      bulkheadService1:
        maxWaitDuration: 0
        maxConcurrentCalls: 1
  thread-pool-bulkhead:
    instances:
      bulkheadService1:
        maxThreadPoolSize: 1
        coreThreadPoolSize: 1
        queueCapacity: 1

feign:
  client:
    config.default.connectTimeout: 4000
    config.default.readTimeout: 4000